### ISSUE TITLE
aur rate limited

### ISSUE THREAD

**Issue by luckyCoderLi** [MiraculousMoon/bspwm-dotfiles#2]
- 你好，仓库里polybar有一个组件update ，它是用来查是否有包更新的，不停发请求会被限流(rate limited)，很多aur的包无法下载，建议将这个情况注明下哈。
- 最后，参考楼主的 bspwm 的配置已经配置好自己的环境，谢谢

**Comment by ayamir** [comment]
Thanks. I have lowered the update frequency.
